name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: multi-platform-build
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        npm install
        pip install pyinstaller
        pip install -r ../backend/requirements.txt
      working-directory: ./frontend
    - name: build
      run: pyinstaller --onefile --hidden-import flask app.py
      working-directory: ./backend
    - name: Save dist artifact
      uses: actions/upload-artifact@v2
      with: 
        name: dist
        path: ./backend/dist/app.exe

